export const CONSTANTS = {
    CREATE_PROCESS: 'CREATE PROCESS',
    REMOVE_PROCESS: 'REMOVE PROCESS',
    PROCESS_NAME: 'PROCESS NAME',
    START_TIME: 'START TIME',
    JOBS_COUNT: 'JOBS COUNT',
    JOB_NAME: 'JOB NAME',
    JOB_PROCESS_ID: 'JOB PROCESS ID',
    JOB_STATUS: 'JOB STATUS',
    PROCESS_JOB_STATUS: 'PROCESS JOB STATUS',
    SORT_BY_NAME: 'SORT BY NAME',
    SORT_BY_START_TIME: 'SORT BY START TIME',
    SORT_BY_JOBS_COUNT: 'SORT BY JOBS COUNT',
    SEARCH_JOB: 'SEARCH JOB',
    FAILING: 'FAILING',
    SUCCESSED: 'SUCCESSED',
    RUNNING: 'RUNNING',
    SEARCH: 'SEARCH',
    START_TIME_FROM: 1,
    START_TIME_TO: 23,
}

export const SORT_KEYS = {
    NAME: 'name',
    START_TIME: 'startTime',
    JOBS_COUNT: 'jobsCount'
}